### ISSUE TITLE
Typo "exension manage"

### ISSUE THREAD

**Issue by berndBergner** [simatic-ax/learning-path#7]
**Describe the bug**
Typo in "01_introduction_to_ax_code/slides.md" line 122.

**Screenshots**
![image](https://github.com/user-attachments/assets/504c102f-161e-49b9-a010-e796f7951b46)

**Comment by sjuergen** [comment]
@berndBergner thanks for creating an issue. I'll fix it. But just as a recommendation: You're welcome to fix it by yourself. I think it's faster in the case of a typo.
